const eventTypes = {
  web: {
    PAGE_VIEW: 'page_view',
    VISIT: 'visit',
    SHOW: 'show',
    HIDE: 'hide',
    DIALOG: 'dialog',
    DIALOG_OPEN: 'dialog_open',
    DIALOG_EXIT: 'dialog_exit',
    MATCHMORE_DIALOG: 'matchmore_dialog',
    MATCHMORE_DIALOG_OPEN: 'matchmore_dialog_open',
    MATCHMORE_DIALOG_EXIT: 'matchmore_dialog_exit',
    MEET_VIEWED: 'meet_viewed',
    REVIEW_REQUEST: 'review_request',
    SOCIAL_LOGIN: 'social_login',
    LINE_CONNECT: 'line_connect',
    REVIEW_CAMPAIGN: 'review_campaign',
    EXPERIMENT: 'experiment',
    CHAT: 'chat',
    FILTER_APPLY: 'filter_apply',
    FILTER_CLEAR: 'filter_clear',
    STARTER_PROGRAM: 'starter_program',
    MUST_PHONE: 'must_phone',
  },
  match_more: {
    SP_RESULT: 'sp_result',
    IRP_SEARCH: 'irp_search',
    IRP_SEARCH_WITH_REQUEST: 'irp_search_with_request',
    CLICK_SP_SEARCH: 'click_sp_search',
    CLICK_SP_TOP_SEARCH: 'click_sp_top_search',
    CLICK_SP_PROFILE: 'click_sp_profile',
    CLICK_SP_SEE_PROFILE: 'click_sp_see_profile',
    CLICK_IRP_PROFILE: 'click_irp_profile',
    CLICK_IRP_SEE_PROFILE: 'click_irp_see_profile',
    OPEN_SP_DIALOG: 'open_sp_dialog',
    OPEN_IRP_DIALOG: 'open_irp_dialog',
    OPEN_PP_DIALOG: 'open_pp_dialog',
    OPEN_ONE_CLICK_IRP_DIALOG: 'open_one_click_irp_dialog',
    OPEN_ONE_CLICK_PP_DIALOG: 'open_one_click_pp_dialog',
    OPEN_RECOMMEND_DIALOG: 'open_recommend_dialog',
    OPEN_IRP_DIALOG_NO_RESULT: 'open_irp_dialog_no_result',
    CONVERSION_SP_DIALOG: 'conversion_sp_dialog',
    CONVERSION_IRP_DIALOG: 'conversion_irp_dialog',
    CONVERSION_IRP_DIALOG_NO_RESULT: 'conversion_irp_dialog_no_result',
    CONVERSION_PP_DIALOG: 'conversion_pp_dialog',
    CONVERSION_ONE_CLICK_IRP_DIALOG: 'conversion_one_click_irp_dialog',
    CONVERSION_ONE_CLICK_PP_DIALOG: 'conversion_one_click_pp_dialog',
    CONVERSION_RECOMMEND_DIALOG: 'conversion_recommend_dialog',
    SCROLL_SP: 'scroll_sp',
  },
}

export default eventTypes
