export {}


// 処理速度向上のため、関連地域のマップは保持する
const nearPrefectures =  {
  all: [ 'tokyo', 'osaka', 'kanagawa', 'fukuoka', 'aichi', 'hokkaido' ],
  tokyo: [ 'saitama', 'kanagawa', 'chiba', 'yamanashi', 'gunma', 'tochigi', 'ibaraki', 'nagano', 'shizuoka' ],
  kanagawa: [ 'tokyo', 'saitama', 'yamanashi', 'chiba', 'shizuoka', 'gunma', 'nagano', 'ibaraki', 'tochigi' ],
  osaka: [ 'nara', 'kyoto', 'hyogo', 'wakayama', 'shiga', 'mie', 'fukui', 'tokushima', 'kagawa' ],
  kyoto: [ 'shiga', 'hyogo', 'osaka', 'fukui', 'nara', 'aichi', 'gifu', 'mie', 'wakayama' ],
  saitama: [ 'tokyo', 'gunma', 'kanagawa', 'tochigi', 'yamanashi', 'ibaraki', 'nagano', 'chiba', 'shizuoka' ],
  tochigi: [ 'gunma', 'ibaraki', 'saitama', 'fukushima', 'tokyo', 'chiba', 'kanagawa', 'yamanashi', 'nagano' ],
  shizuoka: [ 'yamanashi', 'kanagawa', 'aichi', 'tokyo', 'nagano', 'gifu', 'saitama', 'mie', 'gunma' ],
  chiba: [ 'tokyo', 'kanagawa', 'ibaraki', 'saitama', 'tochigi', 'gunma', 'yamanashi', 'shizuoka', 'nagano' ],
  nagano: [ 'yamanashi', 'gunma', 'toyama', 'gifu', 'saitama', 'tokyo', 'kanagawa', 'shizuoka', 'aichi' ],
  hyogo: [ 'kyoto', 'osaka', 'okayama', 'tottori', 'kagawa', 'shiga', 'nara', 'fukui', 'tokushima' ],
  hokkaido: [ 'aomori', 'iwate', 'akita', 'miyagi', 'yamagata', 'fukushima', 'niigata', 'tochigi', 'ibaraki' ],
  aichi: [ 'gifu', 'shiga', 'mie', 'fukui', 'shizuoka', 'nara', 'kyoto', 'yamanashi', 'nagano' ],
  niigata: [ 'yamagata', 'fukushima', 'gunma', 'tochigi', 'toyama', 'nagano', 'saitama', 'ishikawa', 'miyagi' ],
  fukuoka: [ 'saga', 'yamaguchi', 'nagasaki', 'kumamoto', 'oita', 'miyazaki', 'ehime', 'hiroshima', 'shimane' ],
  hiroshima: [ 'shimane', 'ehime', 'okayama', 'kagawa', 'yamaguchi', 'kochi', 'tokushima', 'tottori', 'oita' ],
  ibaraki: [ 'tochigi', 'chiba', 'saitama', 'tokyo', 'gunma', 'fukushima', 'kanagawa', 'yamanashi', 'nagano' ],
  gunma: [ 'saitama', 'tochigi', 'nagano', 'tokyo', 'yamanashi', 'kanagawa', 'ibaraki', 'fukushima', 'niigata' ],
  mie: [ 'nara', 'aichi', 'shiga', 'wakayama', 'osaka', 'kyoto', 'gifu', 'shizuoka', 'fukui' ],
  oita: [ 'yamaguchi', 'fukuoka', 'kumamoto', 'miyazaki', 'ehime', 'saga', 'nagasaki', 'hiroshima', 'kochi' ],
  ishikawa: [ 'toyama', 'fukui', 'gifu', 'nagano', 'shiga', 'kyoto', 'niigata', 'aichi', 'hyogo' ],
  aomori: [ 'akita', 'iwate', 'yamagata', 'miyagi', 'hokkaido', 'fukushima', 'niigata', 'tochigi', 'ibaraki' ],
  iwate: [ 'akita', 'aomori', 'miyagi', 'yamagata', 'fukushima', 'niigata', 'tochigi', 'ibaraki', 'gunma' ],
  miyagi: [ 'fukushima', 'yamagata', 'iwate', 'akita', 'tochigi', 'ibaraki', 'niigata', 'gunma', 'aomori' ],
  akita: [ 'iwate', 'aomori', 'yamagata', 'miyagi', 'fukushima', 'niigata', 'tochigi', 'ibaraki', 'gunma' ],
  yamagata: [ 'fukushima', 'miyagi', 'niigata', 'akita', 'iwate', 'tochigi', 'gunma', 'ibaraki', 'saitama' ],
  fukushima: [ 'tochigi', 'yamagata', 'miyagi', 'ibaraki', 'niigata', 'gunma', 'saitama', 'tokyo', 'chiba' ],
  yamanashi: [ 'nagano', 'kanagawa', 'saitama', 'tokyo', 'shizuoka', 'gunma', 'gifu', 'aichi', 'tochigi' ],
  gifu: [ 'aichi', 'fukui', 'shiga', 'nagano', 'toyama', 'yamanashi', 'kyoto', 'ishikawa', 'shizuoka' ],
  toyama: [ 'ishikawa', 'nagano', 'gifu', 'fukui', 'gunma', 'yamanashi', 'niigata', 'aichi', 'shiga' ],
  fukui: [ 'shiga', 'kyoto', 'gifu', 'aichi', 'ishikawa', 'osaka', 'hyogo', 'toyama', 'nara' ],
  shiga: [ 'kyoto', 'fukui', 'aichi', 'osaka', 'gifu', 'nara', 'mie', 'hyogo', 'wakayama' ],
  nara: [ 'osaka', 'wakayama', 'mie', 'shiga', 'kyoto', 'hyogo', 'aichi', 'tokushima', 'fukui' ],
  wakayama: [ 'nara', 'osaka', 'tokushima', 'mie', 'kagawa', 'hyogo', 'kyoto', 'shiga', 'okayama' ],
  tottori: [ 'okayama', 'hyogo', 'shimane', 'hiroshima', 'kagawa', 'kyoto', 'osaka', 'tokushima', 'fukui' ],
  shimane: [ 'hiroshima', 'okayama', 'tottori', 'yamaguchi', 'ehime', 'kagawa', 'tokushima', 'hyogo', 'kochi' ],
  okayama: [ 'kagawa', 'tottori', 'hyogo', 'hiroshima', 'tokushima', 'shimane', 'osaka', 'ehime', 'kyoto' ],
  yamaguchi: [ 'fukuoka', 'oita', 'hiroshima', 'ehime', 'shimane', 'saga', 'kumamoto', 'nagasaki', 'kochi' ],
  kagawa: [ 'tokushima', 'okayama', 'kochi', 'hiroshima', 'ehime', 'hyogo', 'osaka', 'wakayama', 'tottori' ],
  ehime: [ 'kochi', 'hiroshima', 'kagawa', 'tokushima', 'oita', 'yamaguchi', 'okayama', 'shimane', 'fukuoka' ],
  tokushima: [ 'kagawa', 'kochi', 'okayama', 'wakayama', 'ehime', 'osaka', 'hyogo', 'hiroshima', 'nara' ],
  kochi: [ 'ehime', 'tokushima', 'kagawa', 'hiroshima', 'okayama', 'oita', 'wakayama', 'yamaguchi', 'shimane' ],
  saga: [ 'nagasaki', 'fukuoka', 'kumamoto', 'oita', 'yamaguchi', 'miyazaki', 'ehime', 'hiroshima', 'shimane' ],
  nagasaki: [ 'saga', 'kumamoto', 'fukuoka', 'oita', 'miyazaki', 'yamaguchi', 'ehime', 'hiroshima', 'shimane' ],
  kumamoto: [ 'nagasaki', 'saga', 'fukuoka', 'miyazaki', 'oita', 'yamaguchi', 'ehime', 'kochi', 'hiroshima' ],
  miyazaki: [ 'kumamoto', 'oita', 'nagasaki', 'fukuoka', 'saga', 'ehime', 'yamaguchi', 'kochi', 'hiroshima' ],
  kagoshima: [ 'miyazaki', 'kumamoto', 'okinawa', 'nagasaki', 'saga', 'oita', 'fukuoka', 'yamaguchi', 'ehime' ],
  okinawa: [ 'kagoshima', 'miyazaki', 'kumamoto', 'nagasaki', 'saga', 'oita', 'fukuoka', 'yamaguchi', 'ehime' ],
}

module.exports = {
  nearPrefectures,
}